
Multi-criteria decision making (MCDM) using Topsis


In [1]:
# Installing topsis pelo terminal
#pip install pymcdm

# import nbformat to handle notebook files to call AHP notebook with %run ../AHP/AHP_without_survival.ipynb
# pip install nbformat

In [ ]:
# Imports
# Executar o notebook AHP para carregar os pesos
%run ../../AHP/test/AHP_without_survival.ipynb

# Executar o notebook read_csv para importar o dataframe para teste;
# Posteriormente será importada a classe responsável usada no projecto
%run ../../read_csv_without_survival.ipynb
mydata # <- Dataframe importado com os dados


# Estrutura do DataFrame necessária para o funcionamento do TOPSIS:
# |─────────────|───────────|─────────────────|───────────────────|─────────────────|────────────|
# │ Donor_id    │ HLA Match │ CMV Serostatus  │  Donor Age Group  │ Gender Match    │ ABO Match  │
# ├─────────────┼───────────┼─────────────────┼───────────────────┼─────────────────┼────────────┼
# │ str/object  │ int       │ int             │ int               │ int             │ int        │
# └─────────────┴───────────┴─────────────────┴───────────────────┴─────────────────┴────────────┴


import pandas as pd
import numpy as np
from pymcdm.methods import TOPSIS
from pymcdm.normalizations import vector_normalization

Pesos AHP:
{'HLA': np.float64(0.4295), 'Idade_dador': np.float64(0.3273), 'CMV': np.float64(0.1396), 'ABO': np.float64(0.055), 'Sexo': np.float64(0.0486)}

Consistency Ratio (CR):
0.0076


In [3]:
# Drop the first column and convert to NumPy array
mydata_no_first_column = mydata.iloc[:, 1:].values.astype(int)
mydata_no_first_column

array([[ 7,  0,  0,  0,  0],
       [ 8,  1,  1,  1,  1],
       [ 9,  2,  2,  0,  0],
       [ 7,  3,  0,  1,  0],
       [10,  0,  2,  0,  1],
       [10,  3,  0,  1,  0],
       [ 8,  0,  1,  1,  0],
       [ 9,  1,  0,  0,  1],
       [ 7,  2,  2,  1,  0],
       [10,  0,  1,  0,  1],
       [ 9,  3,  0,  1,  1],
       [ 8,  1,  2,  0,  0],
       [10,  2,  0,  1,  1],
       [ 7,  0,  1,  0,  0],
       [ 9,  1,  1,  1,  0],
       [ 8,  3,  2,  0,  1],
       [10,  0,  0,  1,  0],
       [ 7,  2,  1,  0,  1],
       [ 9,  0,  2,  1,  1],
       [ 8,  1,  0,  0,  0],
       [10,  3,  1,  1,  1],
       [ 7,  1,  2,  0,  0],
       [ 9,  2,  0,  1,  0],
       [ 8,  0,  1,  1,  1],
       [10,  1,  2,  0,  1]])

In [4]:
# Assigning the impacts
# 1 for maximization and -1 for minimization
# Maximize: HLA_match, donor_age_group, ABO_match
# Minimize: CMV_status, Gender_match

i = np.array([1, -1, 1, -1, 1], dtype=int)
i

array([ 1, -1,  1, -1,  1])

In [5]:
# Assigning the weights
# Os pesos foram definidos usando o método de apoio à decisão multicritério AHP (Analytic Hierarchy Process)

# HLA_match=0.4295
# CMV_status=0.1396
# donor_age_group=0.3273
# Gender_match=0.0486
# ABO_match=0.055

# w = np.array([0.4295, 0.1396, 0.3273, 0.0486, 0.055], dtype=float)

# Os pesos abaixo são importados do notebook AHP
w = np.array([peso_HLA, peso_CMV, peso_Idade_dador, peso_Sexo, peso_ABO], dtype=float)
w

array([0.4295, 0.1396, 0.3273, 0.0486, 0.055 ])

In [6]:
# Calling the topsis function
# scores = topsis(
#     data,        # matriz de decisão (alternativas × critérios)
#     weights,     # pesos dos critérios
#     impacts      # impactos: '1' ou '-1'
# )

topsis = TOPSIS(normalization_function=vector_normalization)
resultados = topsis(mydata_no_first_column, w, i)
resultados

c:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymcdm\validators.py:520: UserWarning: Alternatives with indices [4] are dominant. Consider removing them, as such alternatives can cause numerical errors in some methods.
  warn(f'Alternatives with indices {dominant_alts} are dominant. Consider removing them, '
c:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymcdm\validators.py:525: UserWarning: Alternatives with indices [3] are dominated. Consider removing them, as such alternatives can cause numerical errors in some methods.
  warn(f'Alternatives with indices {dominated_alts} are dominated. Consider removing them, '


array([0.31968115, 0.51919198, 0.73955755, 0.        , 1.        ,
       0.20387192, 0.54936358, 0.29348597, 0.68112911, 0.60792451,
       0.18009667, 0.78381701, 0.25569258, 0.5407142 , 0.52214041,
       0.66585645, 0.35330043, 0.46026512, 0.87517636, 0.25504609,
       0.4592858 , 0.74430742, 0.18865538, 0.56439039, 0.87440546])

In [7]:
#1.8 Cria tabela final

# Get the first column
primeira_coluna = mydata.iloc[:, 0]  # Keep as Series

# Convert results to Series
resultados_series = pd.Series(resultados, name='TOPSIS Score')

# Concatenate along columns
df_TOPSIS = pd.concat([primeira_coluna, resultados_series], axis=1)
print(df_TOPSIS)

# Sort by TOPSIS_Score in descending order (highest to lowest)
df_TOPSIS = df_TOPSIS.sort_values(by='TOPSIS Score', ascending=False)
df_TOPSIS.rename(columns={'TOPSIS Score': 'TOPSIS Rank'}, inplace=True)

df_TOPSIS # <- Tabela a ser retornada


   Donor_id  TOPSIS Score
0     IDO01      0.319681
1     IDO02      0.519192
2     IDO03      0.739558
3     IDO04      0.000000
4     IDO05      1.000000
5     IDO06      0.203872
6     IDO07      0.549364
7     IDO08      0.293486
8     IDO09      0.681129
9     IDO10      0.607925
10    IDO11      0.180097
11    IDO12      0.783817
12    IDO13      0.255693
13    IDO14      0.540714
14    IDO15      0.522140
15    IDO16      0.665856
16    IDO17      0.353300
17    IDO18      0.460265
18    IDO19      0.875176
19    IDO20      0.255046
20    IDO21      0.459286
21    IDO22      0.744307
22    IDO23      0.188655
23    IDO24      0.564390
24    IDO25      0.874405


Donor_id  TOPSIS Rank
4     IDO05     1.000000
18    IDO19     0.875176
24    IDO25     0.874405
11    IDO12     0.783817
21    IDO22     0.744307
2     IDO03     0.739558
8     IDO09     0.681129
15    IDO16     0.665856
9     IDO10     0.607925
23    IDO24     0.564390
6     IDO07     0.549364
13    IDO14     0.540714
14    IDO15     0.522140
1     IDO02     0.519192
17    IDO18     0.460265
20    IDO21     0.459286
16    IDO17     0.353300
0     IDO01     0.319681
7     IDO08     0.293486
12    IDO13     0.255693
19    IDO20     0.255046
5     IDO06     0.203872
22    IDO23     0.188655
10    IDO11     0.180097
3     IDO04     0.000000