---
# *Multi-criteria decision making (MCDM) using Topsis*
---

In [1]:
# Installing topsis pelo terminal
#pip install pymcdm

# import nbformat to handle notebook files to call AHP notebook with %run ../AHP/AHP_without_survival.ipynb
# pip install nbformat

In [2]:
# Imports
# Executar o notebook AHP para carregar os pesos
%run ../AHP/AHP.ipynb

# Executar o notebook read_csv para importar o dataframe para teste;
# Posteriormente será importada a classe responsável usada no projecto
%run ../read_csv_without_survival.ipynb
mydata # <- Dataframe importado com os dados
mydata_no_first_column # <- Dataframe importado sem a primeira coluna


import pandas as pd
import numpy as np
from pymcdm.methods import TOPSIS
from pymcdm.normalizations import vector_normalization

Pesos AHP:
{'HLA': np.float64(0.4029), 'Idade_dador': np.float64(0.3088), 'CMV': np.float64(0.1423), 'ABO': np.float64(0.0604), 'Sexo': np.float64(0.0555), 'Survival_Time': np.float64(0.0302)}

Consistency Ratio (CR):
0.0277


In [3]:
# Assigning the impacts
# 1 for maximization and -1 for minimization
# Maximize: HLA_match, donor_age_group, ABO_match
# Minimize: CMV_status, Gender_match

i = np.array([1, -1, 1, -1, 1], dtype=int)
i

array([ 1, -1,  1, -1,  1])

In [4]:
# Assigning the weights
# Os pesos foram definidos usando o método de apoio à decisão multicritério AHP (Analytic Hierarchy Process)

# HLA_match=0.4295
# CMV_status=0.1396
# donor_age_group=0.3273
# Gender_match=0.0486
# ABO_match=0.055

# w = np.array([0.4295, 0.1396, 0.3273, 0.0486, 0.055], dtype=float)

# Os pesos abaixo são importados do notebook AHP
w = np.array([peso_HLA, peso_CMV, peso_Idade_dador, peso_Sexo, peso_ABO], dtype=float)
w

array([0.4029, 0.1423, 0.3088, 0.0555, 0.0604])

In [5]:
# Calling the topsis function
# scores = topsis(
#     data,        # matriz de decisão (alternativas × critérios)
#     weights,     # pesos dos critérios
#     impacts      # impactos: '1' ou '-1'
# )

topsis = TOPSIS(normalization_function=vector_normalization)
resultados = topsis(mydata_no_first_column, w, i)
resultados

c:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymcdm\validators.py:520: UserWarning: Alternatives with indices [4] are dominant. Consider removing them, as such alternatives can cause numerical errors in some methods.
  warn(f'Alternatives with indices {dominant_alts} are dominant. Consider removing them, '
c:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymcdm\validators.py:525: UserWarning: Alternatives with indices [3] are dominated. Consider removing them, as such alternatives can cause numerical errors in some methods.
  warn(f'Alternatives with indices {dominated_alts} are dominated. Consider removing them, '
c:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymcdm\validators.py:578: UserWarning: Weights should be positive and its sum should be equal one. Now, sum of the weights is 0.9699000000000001.
  warn('Weights should be positive and its sum should be equal one. Now, sum of the weights is '


array([0.33794745, 0.52275654, 0.72371298, 0.        , 1.        ,
       0.19957109, 0.55281418, 0.3108075 , 0.66687306, 0.61800755,
       0.18662914, 0.77427471, 0.26168618, 0.54918312, 0.51975059,
       0.6526269 , 0.36449809, 0.46358409, 0.86235877, 0.27115063,
       0.45081688, 0.73831382, 0.19104244, 0.57206654, 0.86716474])

In [6]:
#1.8 Cria tabela final

# Get the first column
primeira_coluna = mydata.iloc[:, 0]  # Keep as Series

# Convert results to Series
resultados_series = pd.Series(resultados, name='TOPSIS Score')

# Concatenate along columns
df_TOPSIS = pd.concat([primeira_coluna, resultados_series], axis=1)
print(df_TOPSIS)

# Sort by TOPSIS_Score in descending order (highest to lowest)
df_TOPSIS = df_TOPSIS.sort_values(by='TOPSIS Score', ascending=False)
df_TOPSIS.rename(columns={'TOPSIS Score': 'TOPSIS Rank'}, inplace=True)

df_TOPSIS # <- Tabela a ser retornada


   Donor_id  TOPSIS Score
0     IDO01      0.337947
1     IDO02      0.522757
2     IDO03      0.723713
3     IDO04      0.000000
4     IDO05      1.000000
5     IDO06      0.199571
6     IDO07      0.552814
7     IDO08      0.310808
8     IDO09      0.666873
9     IDO10      0.618008
10    IDO11      0.186629
11    IDO12      0.774275
12    IDO13      0.261686
13    IDO14      0.549183
14    IDO15      0.519751
15    IDO16      0.652627
16    IDO17      0.364498
17    IDO18      0.463584
18    IDO19      0.862359
19    IDO20      0.271151
20    IDO21      0.450817
21    IDO22      0.738314
22    IDO23      0.191042
23    IDO24      0.572067
24    IDO25      0.867165


Donor_id  TOPSIS Rank
4     IDO05     1.000000
24    IDO25     0.867165
18    IDO19     0.862359
11    IDO12     0.774275
21    IDO22     0.738314
2     IDO03     0.723713
8     IDO09     0.666873
15    IDO16     0.652627
9     IDO10     0.618008
23    IDO24     0.572067
6     IDO07     0.552814
13    IDO14     0.549183
1     IDO02     0.522757
14    IDO15     0.519751
17    IDO18     0.463584
20    IDO21     0.450817
16    IDO17     0.364498
0     IDO01     0.337947
7     IDO08     0.310808
19    IDO20     0.271151
12    IDO13     0.261686
5     IDO06     0.199571
22    IDO23     0.191042
10    IDO11     0.186629
3     IDO04     0.000000