---
# *Multi-criteria decision making (MCDM) using Topsis**
# Usei um dataset do site: https://pt.scribd.com/document/719692081/TOPSIS-Exercise, de forma a comparar os resultados
---

In [ ]:
# 1.1 Installing topsis pelo terminal
#pip install pymcdm

In [1]:
# 1.2 Imports
import pandas as pd
import numpy as np
from pymcdm.methods import TOPSIS
from pymcdm.normalizations import vector_normalization

In [ ]:
# 1.3 Read the dataset
mydata=pd.read_csv('TOPSIS_ex1.csv', sep=';')
mydata

Company  Income  Benefits  TeachingHours  Paperwork 
0      IU       9         8              7           7
1     UEH       8         8              8           8
2     UFM       7         9              8           7
3    TDMU       7         7              7           9
4     FTU       8         7              8           9

In [5]:
# 1.4 Convert the dataset to Matrix
# Drop the first column and convert to NumPy array
d = mydata.iloc[:, 1:].values.astype(float)
d

array([[9., 8., 7., 7.],
       [8., 8., 8., 8.],
       [7., 9., 8., 7.],
       [7., 7., 7., 9.],
       [8., 7., 8., 9.]])

In [6]:
# 1.5 Assigning the impacts
# 1 for maximization and -1 for minimization
# Maximize: Income, Benefits
# Minimize: Teaching Hours, Paperwork

i = np.array([1, 1, -1, -1], dtype=int)
i

array([ 1,  1, -1, -1])

In [7]:
# 1.6 Assigning the weights
# Income=0.3
# Benefits=0.25
# Teaching Hours=0.3
# Paperwork=0.15
w = np.array([0.3, 0.25, 0.3, 0.15], dtype=float)
w

array([0.3 , 0.25, 0.3 , 0.15])

In [8]:
# 1.7 Calling the topsis function
# scores = topsis(
#     data,        # matriz de decisão (alternativas × critérios)
#     weights,     # pesos dos critérios
#     impacts      # impactos: '1' ou '-1'
# )

topsis = TOPSIS(normalization_function=vector_normalization)
resultados = topsis(d, w, i)
resultados

array([0.75646946, 0.4455853 , 0.46183138, 0.27016857, 0.29368747])

In [9]:
#1.8 Cria tabela final

# Get the first column
primeira_coluna = mydata.iloc[:, 0]  # Keep as Series

# Convert results to Series
resultados_series = pd.Series(resultados, name='TOPSIS_Score')

# Concatenate along columns
df = pd.concat([primeira_coluna, resultados_series], axis=1)
df


Company  TOPSIS_Score
0      IU      0.756469
1     UEH      0.445585
2     UFM      0.461831
3    TDMU      0.270169
4     FTU      0.293687