---
# *Multi-criteria decision making (MCDM) using Topsis*
---

In [ ]:
# 1.1 Installing topsis pelo terminal
#pip install pymcdm

In [1]:
# 1.2 Imports
import pandas as pd
import numpy as np
from pymcdm.methods import TOPSIS
from pymcdm.normalizations import vector_normalization

In [2]:
# 1.3 Read the dataset
mydata = pd.read_csv('TOPSIS_project.csv', sep=';', skip_blank_lines=True)
#mydata = mydata.dropna()  # Remove linhas com missing values
mydata

Donor_id  HLA Match  CMV Serostatus\t  Donor Age Group  Gender Match  \
0    IDO01          7                 0                0             0   
1    IDO02          8                 1                1             1   
2    IDO03          9                 2                2             0   
3    IDO04          7                 3                0             1   
4    IDO05         10                 0                2             0   
5    IDO06         10                 3                0             1   

   ABO Match  Expected Survival Time  
0          0                     100  
1          1                     200  
2          0                     300  
3          0                      50  
4          1                     500  
5          0                      40

In [3]:
# 1.4 Convert the dataset to Matrix
# Drop the first column and convert to NumPy array
d = mydata.iloc[:, 1:].values.astype(int)
d

array([[  7,   0,   0,   0,   0, 100],
       [  8,   1,   1,   1,   1, 200],
       [  9,   2,   2,   0,   0, 300],
       [  7,   3,   0,   1,   0,  50],
       [ 10,   0,   2,   0,   1, 500],
       [ 10,   3,   0,   1,   0,  40]])

In [4]:
# 1.5 Assigning the impacts
# 1 for maximization and -1 for minimization
# Maximize: HLA_match, donor_age_group, ABO_match, expected_time_survival
# Minimize: CMV_status, Gender_match

i = np.array([1, -1, 1, -1, 1, 1], dtype=int)
i

array([ 1, -1,  1, -1,  1,  1])

In [5]:
# 1.6 Assigning the weights
# # Os pesos foram definidos usando o método de apoio à decisão multicritério AHP (Analytic Hierarchy Process)

# HLA_match=0.3078
# CMV_status=0.0932
# donor_age_group=0.2216
# Gender_match=0.0336
# ABO_match=0.039
# expected_time_survival=0.3047

w = np.array([0.3078, 0.0932, 0.2216, 0.0336, 0.039, 0.3047], dtype=float)
w

array([0.3078, 0.0932, 0.2216, 0.0336, 0.039 , 0.3047])

In [6]:
# 1.7 Calling the topsis function
# scores = topsis(
#     data,        # matriz de decisão (alternativas × critérios)
#     weights,     # pesos dos critérios
#     impacts      # impactos: '1' ou '-1'
# )

topsis = TOPSIS(normalization_function=vector_normalization)
resultados = topsis(d, w, i)
resultados

c:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymcdm\validators.py:520: UserWarning: Alternatives with indices [4] are dominant. Consider removing them, as such alternatives can cause numerical errors in some methods.
  warn(f'Alternatives with indices {dominant_alts} are dominant. Consider removing them, '


array([0.21422542, 0.4128173 , 0.64514321, 0.01730251, 1.        ,
       0.13712888])

In [7]:
#1.8 Cria tabela final

# Get the first column
primeira_coluna = mydata.iloc[:, 0]  # Keep as Series

# Convert results to Series
resultados_series = pd.Series(resultados, name='TOPSIS Score')

# Concatenate along columns
df = pd.concat([primeira_coluna, resultados_series], axis=1)
print(df)

# Sort by TOPSIS_Score in descending order (highest to lowest)
df = df.sort_values(by='TOPSIS Score', ascending=False)
df.rename(columns={'TOPSIS Score': 'TOPSIS Rank'}, inplace=True)
df


  Donor_id  TOPSIS Score
0    IDO01      0.214225
1    IDO02      0.412817
2    IDO03      0.645143
3    IDO04      0.017303
4    IDO05      1.000000
5    IDO06      0.137129


Donor_id  TOPSIS Rank
4    IDO05     1.000000
2    IDO03     0.645143
1    IDO02     0.412817
0    IDO01     0.214225
5    IDO06     0.137129
3    IDO04     0.017303