
Multi-criteria decision making (MCDM) using Topsis

In [14]:
# Installing topsis pelo terminal
#pip install pymcdm

# import nbformat to handle notebook files to call AHP notebook with %run ../AHP/AHP.ipynb
# pip install nbformat

In [15]:
# Imports
# Executar o notebook AHP para carregar os pesos
%run ../AHP/AHP.ipynb

# Executar o notebook read_csv para importar o dataframe para teste;
# Posteriormente será importada a classe responsável usada no projecto
%run ../read_csv.ipynb
mydata # <- Dataframe importado com os dados
print(mydata)


# Estrutura do DataFrame necessária para o funcionamento do TOPSIS:
# |─────────────|───────────|─────────────────|───────────────────|─────────────────|────────────|─────────────────────────|
# │ Donor_id    │ HLA Match │ CMV Serostatus  │  Donor Age Group  │ Gender Match    │ ABO Match  │ Expected Survival Time  │
# ├─────────────┼───────────┼─────────────────┼───────────────────┼─────────────────┼────────────┼─────────────────────────┤
# │ str/object  │ int       │ int             │ int               │ int             │ int        │ int                     │
# └─────────────┴───────────┴─────────────────┴───────────────────┴─────────────────┴────────────┴─────────────────────────┘


import pandas as pd
import numpy as np
from pymcdm.methods import TOPSIS
from pymcdm.normalizations import vector_normalization

Pesos AHP:
{'HLA': np.float64(0.4029), 'Idade_dador': np.float64(0.3088), 'CMV': np.float64(0.1423), 'ABO': np.float64(0.0604), 'Sexo': np.float64(0.0555), 'Survival_Time': np.float64(0.0302)}

Consistency Ratio (CR):
0.0277


In [16]:
# Drop the first column and convert to NumPy array
mydata_no_first_column = mydata.iloc[:, 1:].values.astype(int)
mydata_no_first_column

array([[   7,    0,    0,    0,    0,  100],
       [   8,    1,    1,    1,    1,  200],
       [   9,    2,    2,    0,    0,  300],
       [   7,    3,    0,    1,    0,   50],
       [  10,    0,    2,    0,    1,  500],
       [  10,    3,    0,    1,    0,   40],
       [   8,    0,    1,    1,    0,  220],
       [   9,    1,    0,    0,    1,  340],
       [   7,    2,    2,    1,    0,   90],
       [  10,    0,    1,    0,    1,  480],
       [   9,    3,    0,    1,    1,  310],
       [   8,    1,    2,    0,    0,  180],
       [  10,    2,    0,    1,    1, 1020],
       [   7,    0,    1,    0,    0,  110],
       [   9,    1,    1,    1,    0,  290],
       [   8,    3,    2,    0,    1,  160],
       [  10,    0,    0,    1,    0,  550],
       [   7,    2,    1,    0,    1,  130],
       [   9,    0,    2,    1,    1,  260],
       [   8,    1,    0,    0,    0,  210],
       [  10,    3,    1,    1,    1,  470],
       [   7,    1,    2,    0,    0,   95],
       [  

In [17]:
# Assigning the impacts
# 1 for maximization and -1 for minimization
# Maximize: HLA_match, donor_age_group, ABO_match, expected_time_survival
# Minimize: CMV_status, Gender_match

i = np.array([1, -1, 1, -1, 1, 1], dtype=int)
i

array([ 1, -1,  1, -1,  1,  1])

In [18]:
# Assigning the weights
# # Os pesos foram definidos usando o método de apoio à decisão multicritério AHP (Analytic Hierarchy Process)


# Os pesos abaixo são importados do notebook AHP
w = np.array([peso_HLA, peso_CMV, peso_Idade_dador, peso_Sexo, peso_ABO, peso_Survival_Time], dtype=float)
w

array([0.4029, 0.1423, 0.3088, 0.0555, 0.0604, 0.0302])

In [19]:
# Calling the topsis function
# scores = topsis(
#     data,        # matriz de decisão (alternativas × critérios)
#     weights,     # pesos dos critérios
#     impacts      # impactos: '1' ou '-1'
# )

topsis = TOPSIS(normalization_function=vector_normalization)
resultados = topsis(mydata_no_first_column, w, i)
resultados

array([0.33541173, 0.51564741, 0.71425442, 0.00146248, 0.92870946,
       0.1978128 , 0.54614963, 0.31074534, 0.65585221, 0.61491279,
       0.18818095, 0.75635445, 0.2801528 , 0.54083697, 0.51455528,
       0.64439978, 0.36639231, 0.45713174, 0.8355335 , 0.26992943,
       0.45062208, 0.72174569, 0.19284258, 0.56518247, 0.8497093 ])

In [20]:
# Cria tabela final

# Get the first column
primeira_coluna = mydata.iloc[:, 0]  # Keep as Series

# Convert results to Series
resultados_series = pd.Series(resultados, name='TOPSIS Score')

# Concatenate along columns
df_TOPSIS = pd.concat([primeira_coluna, resultados_series], axis=1)
print(df_TOPSIS)

# Sort by TOPSIS_Score in descending order (highest to lowest)
df_TOPSIS = df_TOPSIS.sort_values(by='TOPSIS Score', ascending=False)
df_TOPSIS.rename(columns={'TOPSIS Score': 'TOPSIS Rank'}, inplace=True)

df_TOPSIS # <- Tabela a ser retornada

   Donor_id  TOPSIS Score
0     IDO01      0.335412
1     IDO02      0.515647
2     IDO03      0.714254
3     IDO04      0.001462
4     IDO05      0.928709
5     IDO06      0.197813
6     IDO07      0.546150
7     IDO08      0.310745
8     IDO09      0.655852
9     IDO10      0.614913
10    IDO11      0.188181
11    IDO12      0.756354
12    IDO13      0.280153
13    IDO14      0.540837
14    IDO15      0.514555
15    IDO16      0.644400
16    IDO17      0.366392
17    IDO18      0.457132
18    IDO19      0.835534
19    IDO20      0.269929
20    IDO21      0.450622
21    IDO22      0.721746
22    IDO23      0.192843
23    IDO24      0.565182
24    IDO25      0.849709


Donor_id  TOPSIS Rank
4     IDO05     0.928709
24    IDO25     0.849709
18    IDO19     0.835534
11    IDO12     0.756354
21    IDO22     0.721746
2     IDO03     0.714254
8     IDO09     0.655852
15    IDO16     0.644400
9     IDO10     0.614913
23    IDO24     0.565182
6     IDO07     0.546150
13    IDO14     0.540837
1     IDO02     0.515647
14    IDO15     0.514555
17    IDO18     0.457132
20    IDO21     0.450622
16    IDO17     0.366392
0     IDO01     0.335412
7     IDO08     0.310745
12    IDO13     0.280153
19    IDO20     0.269929
5     IDO06     0.197813
22    IDO23     0.192843
10    IDO11     0.188181
3     IDO04     0.001462