---
# *Multi-criteria decision making (MCDM) using Topsis**
---

In [1]:
# 1.1 Installing topsis pelo terminal
#pip install pymcdm

In [2]:
# 1.2 Imports
import pandas as pd
import numpy as np
from pymcdm.methods import TOPSIS
from pymcdm.normalizations import vector_normalization

In [3]:
# 1.3 Read the dataset
mydata=pd.read_csv('TOPSIS_project.csv', sep=';')
mydata

Donor_id  HLA Match  CMV Serostatus\t  Donor Age Group  Gender Match  \
0    IDO01          7                 0                0             0   
1    IDO02          8                 1                1             1   
2    IDO03          9                 2                2             0   
3    IDO04         10                 3                0             1   

   ABO Match  Expected Survival Time  
0          0                     300  
1          1                     500  
2          0                      20  
3          1                      90

In [4]:
# 1.4 Convert the dataset to Matrix
# Drop the first column and convert to NumPy array
d = mydata.iloc[:, 1:].values.astype(int)
d

array([[  7,   0,   0,   0,   0, 300],
       [  8,   1,   1,   1,   1, 500],
       [  9,   2,   2,   0,   0,  20],
       [ 10,   3,   0,   1,   1,  90]])

In [5]:
# 1.5 Assigning the impacts
# 1 for maximization and -1 for minimization
# Maximize: HLA_match, Gender_match, ABO_match
# Minimize: CMV_status, donor_age_group, expected_time_survival

i = np.array([1,-1,-1,1,1,1], dtype=int)
i

array([ 1, -1, -1,  1,  1,  1])

In [6]:
# 1.6 Assigning the weights
# HLA_match=
# CMV_status=
# donor_age_group=
# Gender_match=
# ABO_match=
# expected_time_survival=
w = np.array([0.2857, 0.2381, 0.1905, 0.1429, 0.0952, 0.0476], dtype=float)
w

array([0.2857, 0.2381, 0.1905, 0.1429, 0.0952, 0.0476])

In [7]:
# 1.7 Calling the topsis function
# scores = topsis(
#     data,        # matriz de decisão (alternativas × critérios)
#     weights,     # pesos dos critérios
#     impacts      # impactos: '1' ou '-1'
# )

topsis = TOPSIS(normalization_function=vector_normalization)
resultados = topsis(d, w, i)
resultados

array([0.66007102, 0.64210873, 0.22425132, 0.52621325])

In [8]:
#1.8 Cria tabela final

# Get the first column
primeira_coluna = mydata.iloc[:, 0]  # Keep as Series

# Convert results to Series
resultados_series = pd.Series(resultados, name='TOPSIS Score')

# Concatenate along columns
df = pd.concat([primeira_coluna, resultados_series], axis=1)
print(df)

# Sort by TOPSIS_Score in descending order (highest to lowest)
df = df.sort_values(by='TOPSIS Score', ascending=False)
df.rename(columns={'TOPSIS Score': 'TOPSIS Rank'}, inplace=True)
df


  Donor_id  TOPSIS Score
0    IDO01      0.660071
1    IDO02      0.642109
2    IDO03      0.224251
3    IDO04      0.526213


Donor_id  TOPSIS Rank
0    IDO01     0.660071
1    IDO02     0.642109
3    IDO04     0.526213
2    IDO03     0.224251