---
# *Multi-criteria decision making (MCDM) using Topsis**
# Usei um dataset do site: https://www.sciencedirect.com/science/article/pii/S277266222100014X, de forma a comparar os resultados
---

In [ ]:
# 1.1 Installing topsis pelo terminal
#pip install pymcdm

In [1]:
# 1.2 Imports
import pandas as pd
import numpy as np
from pymcdm.methods import TOPSIS
from pymcdm.normalizations import vector_normalization

In [3]:
# 1.3 Read the dataset
mydata=pd.read_csv('TOPSIS_ex2.csv', sep=';')
mydata

Name  Teaching  Research  Citations  \
0                    University of Oxford      90.5      99.6       98.4   
1      California Institute of Technology      92.1      97.2       97.9   
2                 University of Cambridge      91.4      98.7       95.8   
3                     Stanford University      92.8      96.4       99.9   
4   Massachusetts Institute of Technology      90.5      92.4       99.5   
5                    Princeton University      90.3      96.3       98.8   
6                      Harvard University      89.2      98.6       99.1   
7                         Yale University      92.0      94.8       97.3   
8                   University of Chicago      89.1      91.4       96.7   
9                 Imperial College London      84.5      87.6       97.0   
10             University of Pennsylvania      87.5      90.4       98.2   
11               Johns Hopkins University      81.7      91.4       98.3   
12     University of California, Berkeley      83.0      90.6       99.2   
13                             ETH Zurich      81.8      92.8       90.3   
14                                    UCL      77.8      88.7       96.1   
15                    Columbia University      85.6      82.6       98.2   
16           University of California, LA      83.1      88.6       97.3   
17                  University of Toronto      76.6      89.5       93.6   
18                     Cornell University      79.7      86.0       96.6   
19                        Duke University      82.4      76.8       97.0   

    Industry Income  International Outlook  
0              65.5                   96.4  
1              88.0                   82.5  
2              59.3                   95.0  
3              66.2                   79.5  
4              86.9                   89.0  
5              58.6                   81.1  
6              47.3                   76.3  
7              52.4                   68.7  
8              52.7                   76.0  
9              69.9                   97.1  
10             74.0                   65.0  
11             91.3                   73.2  
12             46.1                   70.4  
13             56.8                   98.2  
14             42.7                   96.2  
15             44.8                   79.3  
16             51.3                   64.1  
17             50.5                   84.7  
18             37.1                   73.4  
19             99.9                   61.5

In [4]:
# 1.4 Convert the dataset to Matrix
# Drop the first column and convert to NumPy array
d = mydata.iloc[:, 1:].values.astype(float)
d

array([[90.5, 99.6, 98.4, 65.5, 96.4],
       [92.1, 97.2, 97.9, 88. , 82.5],
       [91.4, 98.7, 95.8, 59.3, 95. ],
       [92.8, 96.4, 99.9, 66.2, 79.5],
       [90.5, 92.4, 99.5, 86.9, 89. ],
       [90.3, 96.3, 98.8, 58.6, 81.1],
       [89.2, 98.6, 99.1, 47.3, 76.3],
       [92. , 94.8, 97.3, 52.4, 68.7],
       [89.1, 91.4, 96.7, 52.7, 76. ],
       [84.5, 87.6, 97. , 69.9, 97.1],
       [87.5, 90.4, 98.2, 74. , 65. ],
       [81.7, 91.4, 98.3, 91.3, 73.2],
       [83. , 90.6, 99.2, 46.1, 70.4],
       [81.8, 92.8, 90.3, 56.8, 98.2],
       [77.8, 88.7, 96.1, 42.7, 96.2],
       [85.6, 82.6, 98.2, 44.8, 79.3],
       [83.1, 88.6, 97.3, 51.3, 64.1],
       [76.6, 89.5, 93.6, 50.5, 84.7],
       [79.7, 86. , 96.6, 37.1, 73.4],
       [82.4, 76.8, 97. , 99.9, 61.5]])

In [5]:
# 1.5 Assigning the impacts
# 1 for maximization and -1 for minimization
# Maximize: Income, Benefits
# Minimize: Teaching Hours, Paperwork

i = np.array([1, 1, 1, 1, 1], dtype=int)
i

array([1, 1, 1, 1, 1])

In [6]:
# 1.6 Assigning the weights
# Teaching=0.3
# Research=0.3
# Citations Hours=0.3
# Industry Income=0.025
# International Outlook=0.075
w = np.array([0.30, 0.30, 0.30, 0.025, 0.075 ], dtype=float)
w

array([0.3  , 0.3  , 0.3  , 0.025, 0.075])

In [7]:
# 1.7 Calling the topsis function
# scores = topsis(
#     data,        # matriz de decisão (alternativas × critérios)
#     weights,     # pesos dos critérios
#     impacts      # impactos: '1' ou '-1'
# )

topsis = TOPSIS(normalization_function=vector_normalization)
resultados = topsis(d, w, i)
resultados

array([0.85780751, 0.83533823, 0.81829637, 0.79372493, 0.75428354,
       0.76386023, 0.73826343, 0.68917051, 0.62377346, 0.54350468,
       0.57470561, 0.53780747, 0.50917744, 0.53947085, 0.44119406,
       0.41194892, 0.44656898, 0.40099031, 0.34925963, 0.29562445])

In [8]:
#1.8 Cria tabela final

# Get the first column
primeira_coluna = mydata.iloc[:, 0]  # Keep as Series

# Convert results to Series
resultados_series = pd.Series(resultados, name='TOPSIS_Score')

# Concatenate along columns
df = pd.concat([primeira_coluna, resultados_series], axis=1)
df


Name  TOPSIS_Score
0                    University of Oxford      0.857808
1      California Institute of Technology      0.835338
2                 University of Cambridge      0.818296
3                     Stanford University      0.793725
4   Massachusetts Institute of Technology      0.754284
5                    Princeton University      0.763860
6                      Harvard University      0.738263
7                         Yale University      0.689171
8                   University of Chicago      0.623773
9                 Imperial College London      0.543505
10             University of Pennsylvania      0.574706
11               Johns Hopkins University      0.537807
12     University of California, Berkeley      0.509177
13                             ETH Zurich      0.539471
14                                    UCL      0.441194
15                    Columbia University      0.411949
16           University of California, LA      0.446569
17                  University of Toronto      0.400990
18                     Cornell University      0.349260
19                        Duke University      0.295624